server:
  port: 6788
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/apricot_woods_db?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: apricot
    password: woods
#    url: jdbc:mysql://127.0.0.1:62491/remotedb?useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
#    username: cherry78
#    password: red@81319
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5

task:
  execution:
    pool:
      max-threads: 8
      queue-capacity: 20
      keep-alive: 10s
mybatis:
  config-location: classpath:spring/mybatis-config.xml
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.manager.woods.*.entity

manager:
  aeskey: apricot_woods_aes
  md5key: apricot_woods_md5
  passwdKey: apricotKey
  aesJs: apricot_woods